# _config.yml
name: EX/VO
title: "EX/VO"
description: "Surf the cyberweb"

url: "https://www.exhibitionismvoyeurism.com"

baseurl: ""

permalink: "/:year/:month/:day/:title/"
markdown: kramdown
theme: null

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author: "The Dictator"

collections:
  announcements:
    output: true
    permalink: /announcements/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
  - scope:
      path: ""
      type: announcements
    values:
      layout: post
      comments: false
